### ISSUE TITLE
[노티] 댓글 노티 오류

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/diivers#15]
**Describe the bug**
- 제가 작성한 포스트에 진선이가 댓글을 달았는데 해당 댓글에 대한 노티를 제가 받지 못했습니다.

**To Reproduce**

1. 본인의 게시글에 다른 계정으로 댓글을 단다
2. 노티가 오는지 확인한다

**Expected behavior**
- 게시글에 댓글이 달렸다는 노티가 와있어야 한다

**Screenshots**
![스크린샷 2022-05-21 오후 12 48 32](https://user-images.githubusercontent.com/25769209/169634616-8985fb97-ebd1-498e-8a19-98bef34e7add.png)

**Environment**

- Desktop [O]
- Smartphone [O]

**Additional context**

**Comment by h-yes-oo** [comment]
댓글 노티가 매번 생성되는 것이 아니라 업데이트 되는 방식이라 발생한 문제로 추정됩니다 ! 필터링 로직에 이슈가 있어서 진선님이 해당 글에 좋아요를 누르면서 발생한 좋아요 노티에 의해 댓글 노티가 생성되지 않은 것으로 보입니다.

[(#48) 댓글 작성 시 항상 새로운 노티를 생성하도록 수정](https://github.com/ssm0318/adoor/pull/106) PR 로 해결되기를 바라며 같은 문제가 또 발견되면 이슈로 등록하겠습니다 🙂
