### ISSUE TITLE
[노티] 노티 업데이트 시간이 반영되지 않음

### ISSUE THREAD

**Issue by njs03332** [ssm0318/diivers#48]
**Is your feature request related to a problem? Please describe.**
같은 게시물에 댓글을 두번 다는 경우와 같이 노티가 업데이트되어야 할 때, 노티의 시간이 업데이트되지 않음

**Describe the solution you'd like**
노티의 created time이 아닌 updated time이 표시되어야 함

**Describe alternatives you've considered**

**Additional context**

**Comment by ssm0318** [comment]
정렬 기준이 created at이라서 표시도 created at으로 해주고 있는 것도 같은데
updated at으로 정렬기준을 바꿀 경우 노티를 읽었을 때 read/unread column이 변경이 돼서 정렬 순서가 엉망이 됩니다. (지금은 updated at 기준으로 엉망 정렬을 해주고 있는 상태)
아직 확실히는 모르겠지만 updated at과 created at이 아닌 별도의 datetime stamp column을 만들어야 되나 싶기도 한데 이 부분은 백엔드적인 고민도 필요할까 싶어 태그를 추가해봤습니다!

**Comment by GooJinSun** [comment]
제가 버그 상황에 대해 명확하게 이해하고 있지 못한 것 같아 질문드립니다~ @njs03332 

예시로 들어준 "같은 게시물에 댓글을 두 번 다는 경우"는 노티가 '업데이트'되기보다 새로 '생성'되어야 하는 거 아닌가요??🤔

**Comment by ssm0318** [comment]
@GooJinSun  아 지금 구현 상으로는 동일한 노티가 있으면 업데이트 되도록 구현이 되어있어요~ 
노티 테러를 하게 될까봐 그렇게 한 것 같고, 저는 지금도 이미 동일한 노티가 너무 많은 느낌이라 생성보다는 업데이트가 맞다고 생각합니다!

![Screen Shot 2022-09-18 at 4 42 47 PM](https://user-images.githubusercontent.com/25769209/190933167-fe535f28-9f7f-4234-bbf5-75c436d94667.png)

@GooJinSun  요 이슈(#43) 도 비슷한 맥락에서 생성했었습니다!

**Comment by GooJinSun** [comment]
오오 그랬군요!
매번 생성되면 노이즈로 느껴질 수 있을 것 같네요
정렬은 지금처럼 `created_at`으로 유지하되, 프론트에서 `updated_at`을 노출하는 건 어떨까요?
(현재는 `/notifications`에서 `updated_at`을 내려주고 있지는 않네요)

**Comment by ssm0318** [comment]
@GooJinSun 그걸 고민해봤는데 프론트에서 updated_at을 기준으로 정렬을 해줄 경우 노티가 시간순으로 정렬되어 있지 않은 것처럼 보일 것 같아서 그게 고민이었습니다.. (그래도 괜찮을지? 다른 서비스들에서는 그렇게 되어있는 경우가 없는 것 같아서ㅠㅠ) 그래서 created_at도 아니고 updated_at도 아닌 노티 모달에 노출되어야하는 timestamp를 저장하고 있는 칼럼을 하나 추가해서 DB에 저장을 해야되나 고민을 했던거에요!

말씀해주신 방식이 빠른 임시 솔루션은 될 수 있을 것 같아요!

**Comment by GooJinSun** [comment]
뭔가 제가 놓치고 있는 부분이 있는 것 같은데 `created_at`으로 정렬할 경우, `updated_at` 필드를 추가로 보내주는 것이 불가능할까요?
프론트에서는 백에서 (`created_at`으로)정렬해 준 리스트를 노출하되, `updated_at`을 timestamp로 노출하면 어떨까 하는 의견이었습니다!!

**Comment by ssm0318** [comment]
`created_at으로 정렬할 경우, updated_at 필드를 추가로 보내주는 것이 불가능할까요?` <-- 가능합니다!

`프론트에서는 백에서 (created_at으로)정렬해 준 리스트를 노출하되, updated_at을 timestamp로 노출하면 어떨까` <-- 이렇게 하면 created_at와 updated_at 기준으로 정렬했을 때의 순서가 각기 다르니 노티 모달 내의 노티들이 시간이 뒤죽박죽이 될 염려가 있지 않을까요?

예를 들어서
- 노티1 (3주 전에 created): timestamp (2주 전에 updated)
- 노티2 (4주 전에 created): timestamp (1주 전에 updated)
- 노티3 (5주 전에 created): timestamp (3일 전에 updated)
- 노티4 (6주 전에 created): timestamp (3주 전에 updated)
이럴 경우 노티의 정렬 순서는 `노티1 -> 노티2 -> 노티3 -> 노티4` 인데 각 노티의 timestamp가 `2주 전 -> 1주 전 -> 3일 전 -> 3주 전`인게 되니 헷갈리게 보일 것 같다는 의미였어요!
확실하지는 않으나 노티는 보통 timestamp의 최신 순으로 정렬이 되는 것 같아서?

이걸 물어보신게 아니라면 알려주세요!

**Comment by njs03332** [comment]
앗 읽음/안읽음도 updated at에 반영돼서 문제가 생기는군요..!
재원언니 말대로 칼럼을 하나 더 만드는 게 맞을 것 같네요! 굿굿,,,

**Comment by ssm0318** [comment]
다른 서비스들은 어떻게 하고 있는걸까유... 알면 알수록 쉽지 않은 노티의 세계
